import fs from "node:fs/promises";
import { SpreadsheetFile, Workbook } from "file:///C:/Users/rathe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/@oai/artifact-tool/dist/artifact_tool.mjs";

const out = new URL("../downloads/Enterprise_AI_Governance_Greenfield_Implementation_Toolkit.xlsx", import.meta.url).pathname.replace(/^\/(.:)/,"$1");
const wb = Workbook.create();
const navy="#102A4C", gold="#A67C2E", pale="#EEF2F5", ink="#172D42", muted="#5F6F7E";
function title(sh,text,sub,cols){sh.showGridLines=false; sh.getRange(`A1:${cols}1`).merge(); sh.getRange("A1").values=[[text]]; sh.getRange(`A1:${cols}1`).format={fill:navy,font:{bold:true,color:"#FFFFFF",size:16},rowHeight:30}; sh.getRange(`A2:${cols}2`).merge(); sh.getRange("A2").values=[[sub]]; sh.getRange(`A2:${cols}2`).format={font:{color:muted,italic:true},rowHeight:28,wrapText:true};}
function table(sh,range,headers,rows){const all=[headers,...rows]; sh.getRange(range).values=all; const end=range.split(":")[1].replace(/\d+/g,""); sh.getRange(`A4:${end}4`).format={fill:pale,font:{bold:true,color:navy},borders:{preset:"doubleBottom",style:"thin",color:gold},wrapText:true}; sh.getRange(range).format.wrapText=true; sh.freezePanes.freezeRows(4); sh.getRange(range).format.autofitColumns(); sh.getRange(range).format.autofitRows();}
const stages=[
["01","Strategy, Vision & Executive Mandate","Mandate","Executive sponsor","Not Started","Charter, strategy, principles, stakeholder map","Mandate and scope approved"],
["02","Current-State Discovery & Maturity Baseline","Mandate","AI Governance Lead","Not Started","Inventory, maturity baseline, gaps, backlog","Coverage validated"],
["03","Governance Operating Model","Mobilize","AI Governance Lead","Not Started","Operating model, terms of reference, decision calendar","Forums and authority active"],
["04","Accountability, RACI & Decision Rights","Mobilize","Executive sponsor","Not Started","RACI, decision rights, role descriptions","Accountability unambiguous"],
["05","Policy, Standards & Control Framework","Control","Risk / Compliance","Not Started","Policy, standards, control catalogue, mapping","Controls testable and owned"],
["06","Lifecycle Governance & Operating Processes","Control","Product / Technology","Not Started","Playbook, forms, reviews, approvals","Gates auditable"],
["07","AI Risk Management Framework","Control","Enterprise Risk","Not Started","Taxonomy, assessment, risk and exception registers","Risk drives approvals"],
["08","Architecture, Data, Security & Privacy","Control","Enterprise Architecture","Not Started","Reference architecture, ADRs, flows, assessments","Controls tested"],
["09","Enablement, Adoption & Change","Mobilize","Change Lead","Not Started","Change strategy, curriculum, communications, dashboard","Roles demonstrate competence"],
["10","Monitoring, Assurance & Continuous Improvement","Prove","Assurance Lead","Not Started","Metrics, tests, reports, incident playbook, backlog","Findings reach verified closure"]];
let sh=wb.worksheets.add("Implementation Plan"); title(sh,"Greenfield AI Governance Implementation Plan","Editable program tracker. Update owners, dates, status and evidence locations.","J"); table(sh,"A4:J14",["Stage","Workstream","Phase","Accountable owner","Status","Planned start","Planned finish","Deliverables","Exit criterion","Evidence link"],stages.map(r=>[...r.slice(0,5),"","",r[5],r[6],""])); sh.getRange("E5:E104").dataValidation={rule:{type:"list",values:["Not Started","In Progress","At Risk","Blocked","Complete"]}};
sh=wb.worksheets.add("AI Inventory"); title(sh,"Enterprise AI Inventory","Register systems, models, agents, vendor AI and embedded automation before risk assessment.","N"); table(sh,"A4:N9",["AI ID","System / use case","Business owner","Technical owner","Business process","AI type","Autonomy","Data classification","Affected stakeholders","Vendor","Lifecycle status","Risk tier","Production URL / location","Last review"],[["AI-001","Example: document classification","","","Operations","Predictive","Advisory","Internal","Employees","Internal","Discovery","","",""]]); sh.getRange("F5:F204").dataValidation={rule:{type:"list",values:["Predictive","Generative","Agentic","Embedded Vendor AI","Intelligent Automation"]}}; sh.getRange("K5:K204").dataValidation={rule:{type:"list",values:["Idea","Discovery","Design","Build","Validate","Production","Suspended","Retired"]}};
sh=wb.worksheets.add("Governance RACI"); title(sh,"Governance RACI & Decision Rights","Use one accountable owner per decision; C = consulted, I = informed.","K"); table(sh,"A4:K12",["Decision","Board","Executive Sponsor","AI Steering Committee","Business Owner","AI Governance","Risk / Compliance","Security / Privacy","Architecture","Delivery Team","Assurance"],[["Approve AI strategy and risk appetite","I","A","R","C","R","C","C","C","I","I"],["Approve policy and standards","I","A","R","C","R","R","C","C","I","I"],["Approve high-risk use case","I","A","R","R","R","R","R","R","C","I"],["Accept residual risk","I","A","C","R","C","R","C","C","I","I"],["Approve production release","I","I","C","A","C","C","C","R","R","I"],["Approve exception","I","A","R","C","R","R","C","C","I","I"],["Invoke kill switch","I","I","I","A","R","R","R","R","R","I"],["Close assurance finding","I","I","C","R","C","A","C","C","R","R"]]);
sh=wb.worksheets.add("Risk Register"); title(sh,"AI Risk & Exception Register","Assess inherent risk, control effectiveness and residual exposure; link every treatment to evidence.","N"); table(sh,"A4:N9",["Risk ID","AI ID","Risk statement","Category","Impact (1-5)","Likelihood (1-5)","Inherent score","Key controls","Control effectiveness","Residual impact","Residual likelihood","Residual score","Risk owner","Treatment / due date"],[["R-001","AI-001","Example: incorrect classification causes material downstream action","Operational",4,3,null,"Human review; confidence threshold","Partially Effective",3,2,null,"",""]]); sh.getRange("G5").formulas=[["=E5*F5"]]; sh.getRange("G5:G204").fillDown(); sh.getRange("L5").formulas=[["=J5*K5"]]; sh.getRange("L5:L204").fillDown(); sh.getRange("I5:I204").dataValidation={rule:{type:"list",values:["Ineffective","Partially Effective","Effective"]}};
sh=wb.worksheets.add("Control Catalogue"); title(sh,"AI Control Catalogue","Trace control objectives to owners, triggers, evidence, tests and framework references.","L"); table(sh,"A4:L12",["Control ID","Domain","Control objective","Control activity","Applicability trigger","Owner","Frequency","Evidence","Test method","Exception route","NIST AI RMF","ISO 42001"],[["GOV-01","Governance","Maintain accountable ownership","Named business and technical owners recorded before assessment","All AI","AI Governance","Per use case","Approved inventory record","Inspect required fields","AI Steering Committee","GOVERN","Leadership / planning"],["RSK-01","Risk","Apply proportional governance","Risk tier assigned using impact, autonomy, data and reversibility","All AI","Enterprise Risk","Per use case / change","Risk assessment","Reperform classification","Risk acceptance authority","MAP / MEASURE","Risk assessment"],["SEC-01","Security","Prevent unauthorized access","Workload identity and least privilege applied to models, agents, tools and data","Production AI","Security","Continuous","IAM policy and access logs","Sample access and negative test","CISO","MANAGE","Operational control"],["DAT-01","Data","Use data for approved purpose","Classification, lineage, minimization, retention and residency documented","AI using enterprise data","Data Owner","Per use case / change","Data-flow and lineage map","Trace sample dataset","Data Governance Council","MAP","Data governance"],["HUM-01","Human Oversight","Preserve effective intervention","Human review, escalation and kill switch mapped to consequence and confidence","High-impact / autonomous AI","Business Owner","Continuous","Review logs and drill results","Observe sample and exercise kill switch","Executive Sponsor","MANAGE","Operational control"],["MON-01","Monitoring","Detect unacceptable change","Performance, drift, fairness, incidents and business outcomes monitored against thresholds","Production AI","Model / Product Owner","Continuous","Dashboard and alerts","Inspect alerts and breach response","AI Steering Committee","MEASURE / MANAGE","Performance evaluation"],["TPR-01","Third Party","Control vendor dependencies","Contract, model, data, service, exit and incident obligations assessed","Vendor AI","Vendor Owner","Onboarding / annual / change","Due diligence and contract clauses","Inspect vendor evidence","Procurement / Risk","GOVERN / MAP","Supplier control"],["ASM-01","Assurance","Verify design and operation","Independent testing performed based on risk and findings tracked to closure","High-risk AI","Assurance","Annual / event driven","Assurance report","Reperform selected tests","Audit Committee","GOVERN / MANAGE","Internal audit"]]);
sh=wb.worksheets.add("Lifecycle Gates"); title(sh,"Eight-Gate AI Lifecycle","Record evidence and approval conditions before progressing.","K"); table(sh,"A4:K12",["Gate","Decision","Required evidence","Business owner","Risk","Security / Privacy","Architecture","Validation","Decision status","Decision date","Conditions / record link"],[['01 Intake','Proceed to assessment','Use case, value, owner, initial data and vendor details','A','C','C','C','I','Pending','',''],['02 Assess','Assign risk tier and pathway','Risk, regulatory, privacy, security and vendor screening','R','A','R','C','C','Pending','',''],['03 Design','Approve control design','Architecture, data flow, controls, human oversight and test plan','R','C','R','A','C','Pending','',''],['04 Develop','Authorize validation','Model/system card, datasets, prompts, code, tests and traceability','A','C','C','R','C','Pending','',''],['05 Validate','Recommend release','Independent performance, fairness, security, privacy and resilience results','C','C','C','C','A','Pending','',''],['06 Deploy','Authorize production','Release plan, monitoring, rollback, incident and support readiness','A','C','R','R','R','Pending','',''],['07 Monitor','Continue, condition or suspend','Metrics, incidents, drift, control health and business outcomes','A','R','R','C','C','Pending','',''],['08 Retire','Close system and obligations','Data/model disposition, access removal, vendor exit and retained evidence','A','C','R','R','I','Pending','','']]); sh.getRange("I5:I104").dataValidation={rule:{type:"list",values:["Pending","Approved","Approved with Conditions","Rejected","Suspended","Closed"]}};
sh=wb.worksheets.add("Evidence Register"); title(sh,"Governance Evidence Register","Single index of evidence supporting decisions, controls, testing and assurance.","J"); table(sh,"A4:J9",["Evidence ID","AI ID","Stage / gate","Control ID","Artifact","Owner","Location","Version / date","Reviewer","Retention / notes"],[["E-001","AI-001","02 Assess","RSK-01","Risk assessment","","","","",""]]);
sh=wb.worksheets.add("Metrics Dashboard"); title(sh,"Governance Metrics & Executive Dashboard","Enter current and target values. Use trends to identify systemic bottlenecks and control weakness.","G"); table(sh,"A4:G13",["Metric","Category","Definition","Current","Target","Direction","Owner"],[["Inventory coverage","Coverage","Known AI systems with confirmed owners / estimated AI population","",1,"Higher is better","AI Governance"],["High-risk gate compliance","Control","High-risk releases with complete gate evidence / high-risk releases","",1,"Higher is better","Risk"],["Open material exceptions","Risk","Material exceptions not past approved expiry","",0,"Lower is better","Risk"],["Median decision cycle time","Efficiency","Median business days from complete intake to decision","",10,"Lower is better","AI Governance"],["Overdue assurance findings","Assurance","Findings past remediation due date","",0,"Lower is better","Assurance"],["Production monitoring coverage","Operations","Production AI with active thresholds and named response owner","",1,"Higher is better","Operations"],["Kill-switch exercise success","Resilience","High-impact systems completing scheduled containment exercise","",1,"Higher is better","Security"],["Role competency completion","Adoption","Target roles completing required training and assessment","",.95,"Higher is better","Change Lead"],["Vendor evidence currency","Third Party","Material AI vendors with current due diligence","",1,"Higher is better","Vendor Risk"]]); sh.getRange("D5:E13").format.numberFormat="0%";
sh=wb.worksheets.add("Framework Mapping"); title(sh,"Integrated Framework Mapping","Harmonize requirements into one enterprise control system rather than parallel checklists.","H"); table(sh,"A4:H12",["Enterprise domain","Portal model","NIST AI RMF","ISO/IEC 42001","COBIT","Three Lines","DAMA / MRM / EA / ITSM","Primary evidence"],[["Strategy & governance","Governance, Compliance & Oversight","GOVERN","Context, leadership, planning","EDM","Board / management oversight","EA principles","Charter and policy"],["Risk classification","Operational & Behavioural Risk","MAP, MEASURE","Risk assessment","APO12","First / second line","MRM tiering","Risk assessment"],["Data & privacy","Data Security & Privacy","MAP","Operational planning / controls","APO14","First / second line","DAMA","Lineage and privacy assessment"],["Architecture & security","AI Architecture Framework","MAP, MANAGE","Support / operation","APO03, DSS05","First / second line","EA / security architecture","Architecture decision record"],["Third party","Vendor & Infrastructure","GOVERN, MAP","Externally provided processes","APO10","First / second line","ITSM supplier management","Due diligence and contract"],["Lifecycle gates","Agentic AI Governance Framework","All functions","Operation / performance evaluation","BAI","First / second line","MRM / SDLC / ITSM","Gate decision record"],["Monitoring & incidents","Assurance","MEASURE, MANAGE","Performance evaluation / improvement","MEA, DSS","All three lines","MRM / ITSM","Dashboard, incident, test"],["Independent assurance","Security & Architecture Review","GOVERN, MANAGE","Internal audit","MEA","Third line","Audit methodology","Assurance report"]]);
for(const s of wb.worksheets.items){const u=s.getUsedRange(); if(u){u.format.font={name:"Aptos",size:10,color:ink}; s.getRange("A1").format.font={name:"Aptos Display",size:16,bold:true,color:"#FFFFFF"};}}
await fs.mkdir(new URL("../downloads/",import.meta.url),{recursive:true}); const file=await SpreadsheetFile.exportXlsx(wb); await file.save(out); console.log(out);
