import fs from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { Workbook, SpreadsheetFile } from "@oai/artifact-tool";

const outDir = new URL("../work/artifacts/", import.meta.url);
await fs.mkdir(outDir, { recursive: true });

const C = {navy:"#08264A",navy2:"#173F66",gold:"#A98545",cream:"#F7F5EF",grey:"#F3F5F7",line:"#DDE3E8",white:"#FFFFFF",text:"#173047",muted:"#617181",green:"#DDECE4",amber:"#F5E9D5",red:"#F2DDDC",blue:"#E3EDF5",input:"#FFF8E8"};
const titleFmt={fill:C.navy,font:{bold:true,color:C.white,size:18},verticalAlignment:"center"};
const sectionFmt={fill:C.navy2,font:{bold:true,color:C.white,size:11},verticalAlignment:"center"};
const headFmt={fill:C.grey,font:{bold:true,color:C.navy,size:9},wrapText:true,verticalAlignment:"center",borders:{bottom:{style:"thin",color:C.line}}};
const bodyFmt={font:{color:C.text,size:9},verticalAlignment:"top",wrapText:true,borders:{bottom:{style:"thin",color:C.line}}};
const inputFmt={fill:C.input,font:{color:C.text,size:9},verticalAlignment:"top",wrapText:true,borders:{bottom:{style:"thin",color:C.line}}};
function setup(sheet){sheet.showGridLines=false;sheet.freezePanes.freezeRows(5);}
function title(sheet, text, subtitle, endCol){sheet.getRange(`A1:${endCol}1`).merge();sheet.getRange("A1").values=[[text]];sheet.getRange(`A1:${endCol}1`).format=titleFmt;sheet.getRange(`A1:${endCol}1`).format.rowHeight=32;sheet.getRange(`A2:${endCol}2`).merge();sheet.getRange("A2").values=[[subtitle]];sheet.getRange(`A2:${endCol}2`).format={fill:C.cream,font:{color:C.muted,size:9},wrapText:true};sheet.getRange(`A2:${endCol}2`).format.rowHeight=30;}
function widths(sheet, map){for(const [col,width] of Object.entries(map))sheet.getRange(`${col}:${col}`).format.columnWidth=width;}
function addTable(sheet,range,name){const t=sheet.tables.add(range,true,name);t.style="TableStyleMedium2";t.showBandedRows=false;return t;}
function dv(sheet,range,values){sheet.getRange(range).dataValidation={rule:{type:"list",values}};}
function scoreCF(range){range.conditionalFormats.add("colorScale",{colors:[C.red,C.amber,C.green],thresholds:["min","50%","max"]});}

// ---------- Workbook 1: Opportunity Priority Matrix ----------
const wb1=Workbook.create();
const read1=wb1.worksheets.add("Read Me");
const intake=wb1.worksheets.add("Opportunity Intake");
const criteria=wb1.worksheets.add("Scoring Model");
const risks=wb1.worksheets.add("Risk Review");
const tech=wb1.worksheets.add("Technology Dependencies");
const dash=wb1.worksheets.add("Portfolio Dashboard");

title(read1,"AI & RPA Opportunity Priority Matrix","A decision template for comparing automation opportunities using value, feasibility, strategic alignment, risk, technology landscape, and dependency readiness.","H");
read1.getRange("A4:H4").values=[["How to use","Owner","Action","Decision output","Control principle","Score scale","Template status","Version"]];read1.getRange("A4:H4").format=headFmt;
read1.getRange("A5:H10").values=[
 ["1. Capture each candidate in Opportunity Intake.","Business owner","Describe the process and quantify volume, effort, error and impact.","Comparable baseline","Do not automate a poorly understood process.","1=low / weak; 5=high / strong","Editable template","2026-07-19"],
 ["2. Complete risk and technology questions.","Risk + Architecture","Assess data sensitivity, decision impact, resilience, systems, APIs and planned change.","Risk and dependency profile","Higher value never cancels an unacceptable control gap.","Risk: 1=low; 5=very high","Formula driven","Sources in workbook"],
 ["3. Review calculated scores and recommendation.","AI/RPA CoE","Challenge assumptions and compare the portfolio, not isolated ideas.","Do Now / Pilot / Prepare / Defer","Use the score to support—not replace—governance judgment.","Readiness: 1=weak; 5=strong","No macros","Client-tailorable"],
 ["4. Record conditions and decisions.","Governance forum","Approve, reject, defer or request evidence; assign owner and target date.","Auditable decision","High-risk AI requires proportionate testing and human oversight.","All weights total 100%","Risk-adjusted","Enterprise neutral"],
 ["Yellow cells are inputs; blue/green/amber/red cells are calculated or risk signals.","Template custodian","Adjust weights in Scoring Model before portfolio use.","Transparent scoring","Revalidate after material process, data, platform or vendor change.","Use whole numbers 1–5","Protected by convention","Not legal advice"],
 ["Suggested cadence: intake weekly; portfolio prioritization monthly; full refresh quarterly.","Portfolio manager","Archive decisions and evidence references.","Living portfolio","Retain rationale, not only the final score.","Percentages stored as numbers","Source checked","2026-07-19"]
];read1.getRange("A5:H10").format=bodyFmt;read1.getRange("A12:H12").merge();read1.getRange("A12").values=[["Decision sequence: Discover → Qualify → Risk & Architecture Gate → Prioritize → Pilot → Production → Monitor"]];read1.getRange("A12:H12").format={fill:C.blue,font:{bold:true,color:C.navy,size:11},horizontalAlignment:"center"};widths(read1,{A:34,B:18,C:32,D:25,E:34,F:24,G:20,H:18});setup(read1);

const intakeHeaders=["ID","Initiative","Business Unit","Process Owner","Automation Pattern","Process Summary","Monthly Volume","Minutes / Case","Labour Cost / Hour","Error / Rework %","Rule-Based %","Structured Data %","API Availability","UI Stability","Process Maturity","Data Readiness","Architecture Readiness","Strategic Alignment","Customer Impact","Employee Impact","Compliance Benefit","Time Criticality","Sponsor Readiness","Implementation Effort","Integration Complexity","Vendor Dependency","Security & Privacy Risk","Decision / Model Risk","Operational Resilience Risk","Change Impact","Annual Hours","Gross Capacity Value","Value Score","Feasibility Score","Risk Exposure","Dependency Score","Priority Score","Recommendation","Governance Condition","Decision Owner","Target Decision Date","Status"];
title(intake,"Opportunity Intake & Scorecard","Enter one opportunity per row. Yellow columns are inputs; calculated columns translate value, readiness, risk and dependency into a comparable recommendation.","AP");
intake.getRange("A4:AP4").values=[intakeHeaders];intake.getRange("A4:AP4").format=headFmt;intake.getRange("A4:AP4").format.rowHeight=42;
const samples=[
 ["OP-001","Supplier invoice intake","Finance","AP Director","Hybrid AI + RPA","Extract invoice data, validate against PO and post approved items",4500,12,42,0.08,0.85,0.7,"Partial","Stable",4,4,4,5,3,4,4,4,5,3,3,2,3,2,3,3],
 ["OP-002","Employee access provisioning","IT","IAM Manager","RPA / Workflow","Provision standard access after approved request",1200,18,55,0.04,0.95,0.95,"Strong","Stable",5,5,5,4,2,4,5,5,5,2,2,2,4,1,4,2],
 ["OP-003","Customer complaint triage","Operations","CX Director","AI Assist","Classify, summarize and route complaints with human review",2600,9,48,0.1,0.55,0.45,"Partial","Stable",4,3,3,4,5,4,4,5,4,3,3,3,4,4,3,4],
 ["OP-004","Credit approval recommendation","Risk","Lending VP","Decision AI","Recommend credit outcome for human approval",900,35,75,0.03,0.6,0.8,"Strong","Stable",5,4,4,5,5,3,5,5,5,5,4,4,4,5,5,4],
 ["OP-005","Legacy report download","Finance","Controller","RPA","Download, rename and distribute recurring reports",300,22,45,0.02,1,1,"None","Changing",3,5,2,3,1,3,2,3,4,2,3,4,2,1,3,3],
 ["OP-006","Contract clause review","Legal","General Counsel","AI Assist","Identify clauses and deviations for counsel review",420,50,120,0.06,0.45,0.3,"Partial","Stable",3,3,3,4,4,4,5,4,4,4,4,3,4,4,3,4]
];
for(let i=0;i<30;i++){
 const row=5+i;const s=samples[i]||Array(30).fill("");
 intake.getRange(`A${row}:AD${row}`).values=[[...s]];
 intake.getRange(`AE${row}:AP${row}`).formulas=[[
  `=IF(OR(G${row}="",H${row}=""),"",G${row}*12*H${row}/60)`,
  `=IF(AE${row}="","",AE${row}*I${row})`,
  `=IF(A${row}="","",ROUND((MIN(5,AE${row}/1000)*25+MIN(5,AF${row}/100000)*25+R${row}*15+S${row}*10+T${row}*10+U${row}*10+V${row}*5)/5,1))`,
  `=IF(A${row}="","",ROUND(((K${row}*5)+(L${row}*5)+IF(M${row}="Strong",25,IF(M${row}="Partial",15,5))+IF(N${row}="Stable",20,IF(N${row}="Mixed",12,5))+O${row}*5+P${row}*5+Q${row}*5-W${row}*2)/5,1))`,
  `=IF(A${row}="","",ROUND((AA${row}*25+AB${row}*25+AC${row}*25+AD${row}*25)/5,1))`,
  `=IF(A${row}="","",ROUND((X${row}*30+Y${row}*30+Z${row}*25+AD${row}*15)/5,1))`,
  `=IF(A${row}="","",ROUND(AG${row}*'Scoring Model'!$B$5+AH${row}*'Scoring Model'!$B$6+(100-AI${row})*'Scoring Model'!$B$7+(100-AJ${row})*'Scoring Model'!$B$8,1))`,
  `=IF(A${row}="","",IF(OR(AA${row}=5,AB${row}=5,AC${row}=5),"Pilot with Controls",IF(AK${row}>=75,"Do Now",IF(AK${row}>=60,"Pilot with Controls",IF(AK${row}>=45,"Prepare / Remediate","Defer")))))`,
  `=IF(A${row}="","",IF(OR(AA${row}=5,AB${row}=5,AC${row}=5),"Enhanced risk, testing, human oversight and approval required",IF(AJ${row}>=70,"Resolve architecture / vendor dependencies before commitment","Standard lifecycle controls")))`,"","",`=IF(A${row}="","","Draft")`
 ]];
}
intake.getRange("A5:AD34").format=inputFmt;intake.getRange("AE5:AP34").format=bodyFmt;intake.getRange("G5:I34").format.numberFormat="#,##0.0";intake.getRange("J5:L34").format.numberFormat="0%";intake.getRange("AE5:AF34").format.numberFormat="#,##0";intake.getRange("AG5:AK34").format.numberFormat="0.0";intake.getRange("AO5:AO34").format.numberFormat="yyyy-mm-dd";
dv(intake,"E5:E34",["RPA","Workflow / API","AI Assist","Decision AI","Agentic AI","Hybrid AI + RPA"]);dv(intake,"M5:M34",["None","Partial","Strong"]);dv(intake,"N5:N34",["Changing","Mixed","Stable"]);for(const c of ["O","P","Q","R","S","T","U","V","W","X","Y","Z","AA","AB","AC","AD"])dv(intake,`${c}5:${c}34`,[1,2,3,4,5]);dv(intake,"AP5:AP34",["Draft","Under Review","Approved","Pilot","Production","Deferred","Rejected"]);
scoreCF(intake.getRange("AG5:AK34"));intake.getRange("AL5:AL34").conditionalFormats.add("containsText",{text:"Do Now",format:{fill:C.green,font:{bold:true,color:"#245C3C"}}});intake.getRange("AL5:AL34").conditionalFormats.add("containsText",{text:"Pilot",format:{fill:C.amber,font:{bold:true,color:"#7A5617"}}});intake.getRange("AL5:AL34").conditionalFormats.add("containsText",{text:"Defer",format:{fill:C.red,font:{bold:true,color:"#8B302A"}}});
addTable(intake,"A4:AP34","OpportunityPortfolio");widths(intake,{A:12,B:28,C:18,D:20,E:20,F:36,G:14,H:14,I:16,J:14,K:14,L:16,M:16,N:14,O:15,P:15,Q:18,R:15,S:15,T:15,U:17,V:14,W:16,X:17,Y:18,Z:16,AA:18,AB:18,AC:18,AD:14,AE:16,AF:19,AG:14,AH:15,AI:14,AJ:15,AK:14,AL:22,AM:40,AN:18,AO:17,AP:14});setup(intake);intake.freezePanes.freezeColumns(6);

title(criteria,"Scoring Model & Guidance","Adjust the four portfolio weights below. Input ratings use a 1–5 scale; formulas normalize outputs to 0–100.","G");criteria.getRange("A4:G4").values=[["Dimension","Weight","What it measures","1 — Low","3 — Moderate","5 — High","Decision use"]];criteria.getRange("A4:G4").format=headFmt;
criteria.getRange("A5:G8").values=[
 ["Value",0.35,"Capacity, cost, quality, customer, employee, compliance and urgency","Limited local benefit","Material team benefit","Enterprise / mission critical benefit","Prioritizes outcomes"],
 ["Feasibility",0.25,"Rules, data, APIs, UI stability, maturity, readiness and effort","Unclear / unstable","Some remediation","Ready and repeatable","Tests delivery practicality"],
 ["Risk-adjusted fit",0.2,"Security, privacy, model/decision and resilience exposure","Very high exposure","Manageable with controls","Low exposure","Prevents value-only selection"],
 ["Dependency-adjusted fit",0.2,"Effort, integration, vendor and change dependencies","Multiple critical blockers","Manageable dependencies","Low dependency / native fit","Protects architecture alignment"]
];criteria.getRange("A5:G8").format=bodyFmt;criteria.getRange("B5:B8").format=inputFmt;criteria.getRange("B5:B8").format.numberFormat="0%";criteria.getRange("A10").values=[["Weight check"]];criteria.getRange("B10").formulas=[["=SUM(B5:B8)"]];criteria.getRange("A10:B10").format=sectionFmt;criteria.getRange("B10").format.numberFormat="0%";criteria.getRange("A12:G12").values=[["Recommendation","Priority threshold","Required interpretation","Risk override","Typical next step","Evidence","Owner"]];criteria.getRange("A12:G12").format=headFmt;criteria.getRange("A13:G16").values=[["Do Now",75,"Strong value and readiness with acceptable exposure","Any risk=5 changes result to Pilot with Controls","Approve discovery / delivery","Business case + gate evidence","Governance forum"],["Pilot with Controls",60,"Promising but uncertainty or high-risk condition remains","Mandatory enhanced controls","Time-boxed pilot","Test plan + risk acceptance","Business + Risk"],["Prepare / Remediate",45,"Value exists but readiness or dependencies constrain delivery","Resolve blockers first","Data/process/architecture remediation","Remediation plan","Capability owner"],["Defer",0,"Weak case or disproportionate complexity","Do not bypass","Reassess after material change","Decision rationale","Portfolio owner"]];criteria.getRange("A13:G16").format=bodyFmt;widths(criteria,{A:24,B:16,C:38,D:32,E:28,F:30,G:20});setup(criteria);

title(risks,"Risk Review","Complete a focused risk record for every shortlisted AI, RPA or hybrid initiative. Link evidence and define the treatment owner.","L");const riskHeads=["Opportunity ID","Risk Domain","Risk Statement","Likelihood (1–5)","Impact (1–5)","Inherent Risk","Control / Treatment","Control Owner","Residual Likelihood","Residual Impact","Residual Risk","Evidence / Decision Link"];risks.getRange("A4:L4").values=[riskHeads];risks.getRange("A4:L4").format=headFmt;for(let r=5;r<=44;r++){risks.getRange(`A${r}:E${r}`).format=inputFmt;risks.getRange(`F${r}`).formulas=[[`=IF(OR(D${r}="",E${r}=""),"",D${r}*E${r})`]];risks.getRange(`G${r}:J${r}`).format=inputFmt;risks.getRange(`K${r}`).formulas=[[`=IF(OR(I${r}="",J${r}=""),"",I${r}*J${r})`]];risks.getRange(`L${r}`).format=inputFmt;}dv(risks,"B5:B44",["Privacy","Security","Model / Decision","Operational Resilience","Regulatory","Third Party","Data","Architecture","Change / Workforce","Financial"]);for(const c of ["D","E","I","J"])dv(risks,`${c}5:${c}44`,[1,2,3,4,5]);scoreCF(risks.getRange("F5:F44"));scoreCF(risks.getRange("K5:K44"));addTable(risks,"A4:L44","RiskRegister");widths(risks,{A:15,B:22,C:42,D:16,E:15,F:14,G:42,H:20,I:18,J:16,K:14,L:35});setup(risks);

title(tech,"Technology Landscape & Dependencies","Map the current and target environment before choosing a tool. Native fit can reduce cost and complexity, but must not override capability, control, or portability needs.","M");const techHeads=["Opportunity ID","System / Platform","Role in Process","Current / Target","Integration Method","API Quality (1–5)","Identity / Access","Data Classification","Hosting / Region","Planned Change","Dependency Criticality","Mitigation / Design Decision","Owner"];tech.getRange("A4:M4").values=[techHeads];tech.getRange("A4:M4").format=headFmt;tech.getRange("A5:M34").format=inputFmt;dv(tech,"D5:D34",["Current","Target","Transitional","Retiring"]);dv(tech,"E5:E34",["Native connector","REST API","Event / Queue","Database","File / Batch","UI automation","Manual handoff"]);dv(tech,"F5:F34",[1,2,3,4,5]);dv(tech,"H5:H34",["Public","Internal","Confidential","Highly Restricted"]);dv(tech,"K5:K34",["Low","Moderate","High","Critical"]);addTable(tech,"A4:M34","TechnologyDependencyRegister");widths(tech,{A:15,B:26,C:30,D:16,E:20,F:16,G:24,H:19,I:22,J:24,K:20,L:42,M:20});setup(tech);

title(dash,"Portfolio Dashboard","Formula-driven portfolio view. Update Opportunity Intake and this page recalculates.","J");dash.getRange("A4:J4").values=[["Portfolio KPI","Value","","Recommendation","Count","","Risk / Readiness KPI","Value","","Interpretation"]];dash.getRange("A4:J4").format=headFmt;dash.getRange("A5:B10").values=[["Total opportunities",""],["Do Now",""],["Pilot with Controls",""],["Prepare / Remediate",""],["Defer",""],["Approved / Pilot / Production",""]];dash.getRange("B5:B10").formulas=[["=COUNTIF('Opportunity Intake'!$A$5:$A$34,\"OP-*\")"],["=COUNTIF('Opportunity Intake'!$AL$5:$AL$34,\"Do Now\")"],["=COUNTIF('Opportunity Intake'!$AL$5:$AL$34,\"Pilot with Controls\")"],["=COUNTIF('Opportunity Intake'!$AL$5:$AL$34,\"Prepare / Remediate\")"],["=COUNTIF('Opportunity Intake'!$AL$5:$AL$34,\"Defer\")"],["=COUNTIF('Opportunity Intake'!$AP$5:$AP$34,\"Approved\")+COUNTIF('Opportunity Intake'!$AP$5:$AP$34,\"Pilot\")+COUNTIF('Opportunity Intake'!$AP$5:$AP$34,\"Production\")"]];dash.getRange("D5:E8").values=[["Do Now",""],["Pilot with Controls",""],["Prepare / Remediate",""],["Defer",""]];dash.getRange("E5:E8").formulas=[["=B6"],["=B7"],["=B8"],["=B9"]];dash.getRange("G5:H10").values=[["Average priority",""],["Average risk exposure",""],["Average feasibility",""],["High-risk opportunities",""],["Annual hours identified",""],["Gross capacity value",""]];dash.getRange("H5:H10").formulas=[["=IFERROR(AVERAGE('Opportunity Intake'!$AK$5:$AK$34),0)"],["=IFERROR(AVERAGE('Opportunity Intake'!$AI$5:$AI$34),0)"],["=IFERROR(AVERAGE('Opportunity Intake'!$AH$5:$AH$34),0)"],["=COUNTIF('Opportunity Intake'!$AI$5:$AI$34,\">=80\")"],["=SUM('Opportunity Intake'!$AE$5:$AE$34)"],["=SUM('Opportunity Intake'!$AF$5:$AF$34)"]];dash.getRange("J5:J10").values=[["Use with risk and dependency review"],["Higher means more control intensity"],["Readiness, process and technology fit"],["Any risk dimension rated 5"],["Capacity indicator—not guaranteed savings"],["Before implementation and run costs"]];dash.getRange("A5:J10").format=bodyFmt;dash.getRange("B5:B10").format={fill:C.blue,font:{bold:true,color:C.navy,size:13}};dash.getRange("H5:H10").format={fill:C.cream,font:{bold:true,color:C.navy,size:13}};dash.getRange("H5:H7").format.numberFormat="0.0";dash.getRange("H9:H10").format.numberFormat="#,##0";const ch=dash.charts.add("bar",dash.getRange("D4:E8"));ch.title="Portfolio by Recommendation";ch.hasLegend=false;ch.setPosition("A13","J30");widths(dash,{A:28,B:16,C:3,D:26,E:14,F:3,G:28,H:16,I:3,J:36});setup(dash);

await wb1.comments.setSelf({displayName:"Ratheesh Technology Ltd."});
const out1=await SpreadsheetFile.exportXlsx(wb1);await out1.save(fileURLToPath(new URL("AI_RPA_Opportunity_Priority_Matrix.xlsx",outDir)));

// ---------- Workbook 2: Platform-Aligned Tool Selection ----------
const wb2=Workbook.create();
const read2=wb2.worksheets.add("Read Me");
const landscape=wb2.worksheets.add("Client Platform Landscape");
const req=wb2.worksheets.add("Selection Criteria");
const resources=wb2.worksheets.add("Resource Capacity");
const catalog=wb2.worksheets.add("Tool Catalogue");
const score=wb2.worksheets.add("Tool Scorecard");
const decision=wb2.worksheets.add("Decision Record");
const sources=wb2.worksheets.add("Official Sources");

title(read2,"AI & RPA Platform-Aligned Tool Selection","A vendor-neutral decision workbook that rewards fit with the client’s existing platform while preserving capability, governance, portability and risk requirements.","H");read2.getRange("A4:H4").values=[["Step","Question","Why it matters","Output","Guardrail","Owner","Status","Version"]];read2.getRange("A4:H4").format=headFmt;read2.getRange("A5:H10").values=[
 ["1. Baseline","Which platforms, identity, data, integration and skills already exist?","Existing investment can reduce time, cost and control duplication.","Landscape profile","Native fit is an accelerator, not an automatic winner.","Enterprise Architecture","Editable","2026-07-19"],
 ["2. Requirements","Which RPA, AI, agent, document, mining, deployment and control capabilities matter?","Weights must reflect the use case and operating model.","Weighted criteria","Weights must total 100%.","Business + CoE","Formula driven","No macros"],
 ["3. Catalogue","Validate product capabilities against current official sources.","Features and licensing change frequently.","Auditable evidence","Run a proof of capability for mandatory features.","Technology owner","Source linked","Checked 2026-07-19"],
 ["4. Score","Rate each tool and review calculated platform alignment.","Separates product capability from ecosystem convenience.","Ranked shortlist","A high score does not replace security, legal or procurement review.","Evaluation team","Client specific","Reusable"],
 ["5. Validate","Pilot the top two or three tools using the same scenarios and test data.","Vendor claims are not production evidence.","Comparable test results","Include failure, resilience and exit tests.","Architecture + Risk","Evidence required","Enterprise neutral"],
 ["6. Decide","Record rationale, conditions, dissent, cost and exit strategy.","Prevents opaque platform lock-in.","Auditable decision","Reassess after material platform or pricing change.","Governance forum","Approval gate","Not procurement advice"]
];read2.getRange("A5:H10").format=bodyFmt;widths(read2,{A:14,B:35,C:35,D:24,E:38,F:24,G:18,H:18});setup(read2);

title(landscape,"Client Platform Landscape","Rate current adoption from 0 (not used) to 5 (strategic standard). The scorecard uses these ratings to calculate ecosystem alignment.","F");landscape.getRange("A4:F4").values=[["Platform Ecosystem","Adoption (0–5)","Current Footprint / Products","Strategic Direction","Constraints / Commitments","Evidence Owner"]];landscape.getRange("A4:F4").format=headFmt;landscape.getRange("A5:F12").values=[
 ["Microsoft",5,"Microsoft 365, Entra ID, Azure, Power Platform, Dynamics / Fabric","Strategic","Tenant, DLP, region, licensing and ALM","Enterprise Architecture"],
 ["AWS",1,"AWS accounts, IAM, data and application services","Selective","Region, network, security and FinOps","Cloud Platform"],
 ["Google Cloud",0,"GCP, Workspace, BigQuery, Vertex AI","Not standard","Identity, data and operating model","Cloud Platform"],
 ["ServiceNow",3,"ITSM / CSM / workflow platform","Strategic for service workflows","License and process scope","Service Management"],
 ["Salesforce",2,"CRM, Service Cloud, Data Cloud","Business critical","Data, integration and platform ownership","CRM Owner"],
 ["SAP",3,"ERP and business process landscape","Strategic core","Clean core and integration standards","ERP Owner"],
 ["IBM / Red Hat",1,"IBM software, OpenShift or watsonx","Selective","Hybrid platform standards","Platform Owner"],
 ["Oracle",1,"Oracle applications / database / cloud","Selective","Data and application roadmap","Platform Owner"]
];landscape.getRange("A5:F12").format=inputFmt;dv(landscape,"B5:B12",[0,1,2,3,4,5]);addTable(landscape,"A4:F12","ClientPlatformProfile");widths(landscape,{A:24,B:18,C:42,D:24,E:42,F:24});setup(landscape);

title(req,"Selection Criteria & Weights","Adjust weights to reflect the client and target use cases. Importance scores are applied consistently to every tool.","H");req.getRange("A4:H4").values=[["Criterion","Weight","Mandatory?","What good looks like","Evidence expected","RPA relevance","AI relevance","Risk if weak"]];req.getRange("A4:H4").format=headFmt;const criteriaRows=[
 ["Core RPA / UI automation",0.1,"Conditional","Reliable attended/unattended desktop and web automation","Demo, supported apps, resilience test","High","Low","Fragile automations"],
 ["Workflow, API and orchestration",0.1,"Yes","API-first orchestration with queues, events, human tasks and retries","Architecture and failure test","High","High","Point automation sprawl"],
 ["AI agents and model flexibility",0.1,"Conditional","Build, orchestrate and evaluate agents; suitable model choice","Agent test and model options","Medium","High","Lock-in or uncontrolled autonomy"],
 ["Document and unstructured data",0.07,"Conditional","Extraction, classification, validation and human review","Accuracy test by document class","High","High","Poor data quality"],
 ["Process / task discovery",0.04,"No","Evidence-based opportunity discovery and process insight","Discovery output and privacy design","High","Medium","Weak pipeline"],
 ["Integration ecosystem",0.11,"Yes","Native and custom connectors aligned to enterprise systems","Connector inventory and API test","High","High","High integration cost"],
 ["Governance, security and audit",0.13,"Yes","RBAC, environments, DLP/policy, logs, approvals and evidence","Control mapping and audit trail","High","High","Control failure"],
 ["Deployment and data location",0.07,"Yes","Required cloud, hybrid/on-prem, region and network patterns","Deployment architecture","High","High","Regulatory / operational mismatch"],
 ["Operations and observability",0.07,"Yes","Monitoring, analytics, incidents, versioning and supportability","Runbook and dashboard","High","High","Unmanaged production"],
 ["Resource availability and delivery capacity",0.08,"Conditional","Sufficient internal skills, hiring market, partners, training, support, ownership and delivery capacity","Named-resource plan, market evidence, partner capacity, support model and skills-gap remediation","High","High","Selection cannot be implemented or sustained"],
 ["Commercial and TCO fit",0.06,"Yes","Transparent licenses, consumption, infrastructure and support costs","3-year TCO and sensitivity","High","High","Cost escalation"],
 ["Portability and exit",0.04,"Yes","Data/model/workflow export, standards and feasible replacement","Exit design and test","Medium","High","Strategic lock-in"],
 ["Existing platform alignment",0.03,"No","Uses existing identity, data, integration, operations and commercial agreements","Landscape score","High","High","Duplicate platform cost"]
];req.getRange("A5:H17").values=criteriaRows;req.getRange("A5:H17").format=bodyFmt;req.getRange("B5:C17").format=inputFmt;req.getRange("B5:B17").format.numberFormat="0%";dv(req,"C5:C17",["Yes","No","Conditional"]);req.getRange("A19").values=[["Weight check"]];req.getRange("B19").formulas=[["=SUM(B5:B17)"]];req.getRange("A19:B19").format=sectionFmt;req.getRange("B19").format.numberFormat="0%";widths(req,{A:30,B:14,C:14,D:44,E:34,F:16,G:16,H:32});setup(req);

title(resources,"Resource Availability & Delivery Capacity","Rate each dimension from 0 (unavailable) to 5 (proven capacity). Product capability is irrelevant if the client cannot implement, govern, operate and support it sustainably.","M");
resources.getRange("A4:M4").values=[["Tool / Platform","Existing Team Reuse","Internal Skills","Recruitment Market","Implementation Partners","Training / Certification","Vendor Support Coverage","Named Operating Owner","Delivery Capacity","Retention / Continuity","Resource Score","Gap / Remediation Action","Evidence Owner"]];resources.getRange("A4:M4").format=headFmt;
const resourceRows=[
 ["Microsoft Power Automate + Copilot Studio",5,4,5,5,5,5,4,4,4],
 ["UiPath Platform",3,4,4,5,5,5,4,4,4],
 ["Automation Anywhere 360",3,3,4,4,4,5,4,4,4],
 ["SS&C Blue Prism",3,3,3,4,4,4,4,3,3],
 ["ServiceNow Workflow Data Fabric / Automation",4,4,4,5,5,5,4,4,4],
 ["Amazon Bedrock",3,3,5,5,5,5,3,3,4],
 ["Google Vertex AI",2,3,4,5,5,5,3,3,4],
 ["IBM watsonx Orchestrate",2,3,3,4,4,5,3,3,3],
 ["OpenAI API Platform",2,3,5,5,5,5,3,3,4]
];
for(let i=0;i<resourceRows.length;i++){const r=5+i;resources.getRange(`A${r}:J${r}`).values=[[...resourceRows[i]]];resources.getRange(`K${r}`).formulas=[[`=ROUND(AVERAGE(B${r}:J${r}),1)`]];resources.getRange(`L${r}:M${r}`).values=[["",""]];}
resources.getRange("A5:A13").format=bodyFmt;resources.getRange("B5:J13").format=inputFmt;resources.getRange("K5:K13").format={fill:C.blue,font:{bold:true,color:C.navy,size:11}};resources.getRange("L5:M13").format=inputFmt;for(const c of ["B","C","D","E","F","G","H","I","J"])dv(resources,`${c}5:${c}13`,[0,1,2,3,4,5]);scoreCF(resources.getRange("K5:K13"));addTable(resources,"A4:M13","ResourceCapacityAssessment");widths(resources,{A:34,B:18,C:16,D:19,E:23,F:22,G:22,H:20,I:18,J:20,K:16,L:46,M:22});setup(resources);resources.freezePanes.freezeColumns(1);

const toolHeaders=["Tool / Platform","Primary Position","Best-fit Client Context","RPA / UI","Workflow / API","AI Agents","Documents","Discovery","Governance","Deployment","Operations","Low-code","Pro-code","Microsoft Affinity","AWS Affinity","Google Affinity","ServiceNow Affinity","Salesforce Affinity","SAP Affinity","IBM Affinity","Oracle Affinity","Key Strengths","Watch-outs / Validate","Official Source ID"];
title(catalog,"Leading AI & RPA Tool Catalogue","Plain-language feature comparison. Ratings are starting assumptions (1–5), not a substitute for client validation or a current licensing review.","X");catalog.getRange("A4:X4").values=[toolHeaders];catalog.getRange("A4:X4").format=headFmt;
const toolRows=[
 ["Microsoft Power Automate + Copilot Studio","Microsoft-native automation and agents","Microsoft 365 / Azure / Dynamics / Power Platform estates",4,5,5,4,3,5,4,4,5,3,5,2,2,3,2,2,2,2,"Cloud flows, desktop flows, connectors, agents, Teams/M365 channels, Power Platform DLP and environments","Licensing, environment strategy, premium connectors, unattended capacity, complex pro-code needs","SRC-001; SRC-002; SRC-003"],
 ["UiPath Platform","Broad enterprise automation","Heterogeneous estates requiring deep RPA, discovery and documents",5,4,4,5,5,5,5,5,4,4,3,3,3,3,3,4,3,3,"Mature RPA, process/task mining, document understanding, orchestration, attended and unattended automation","Platform breadth, licensing/TCO, operating-model discipline, overlap with existing low-code platforms","SRC-004; SRC-005"],
 ["Automation Anywhere 360","Cloud/hybrid agentic process automation","Enterprises prioritizing RPA, discovery, IDP and AI-agent orchestration",5,4,4,4,5,4,5,4,5,4,3,3,3,3,3,3,3,3,"RPA, Agentic Process Automation, AI Agent Studio, Process Discovery, IQ Bot, Bot Insight, cloud/on-prem options","Edition availability, regional features, licensing, integration depth and governance operating model","SRC-006; SRC-007"],
 ["SS&C Blue Prism","Controlled enterprise RPA","Regulated operations emphasizing centrally governed digital workers",5,3,2,3,3,5,5,4,3,3,3,3,2,2,2,3,3,3,"Centralized RPA control, reusable objects, queues, auditability, hybrid deployment patterns","Validate current AI/agent roadmap, modern developer experience, connector ecosystem and total cost","SRC-008"],
 ["ServiceNow Workflow Data Fabric / Automation","Service workflow automation","ServiceNow-centric IT, employee, customer or operations workflows",3,5,4,4,3,5,4,5,4,5,3,3,3,5,3,2,2,2,"IntegrationHub, RPA Hub, Automation Center and Document Intelligence on ServiceNow workflows","Best when work is anchored in ServiceNow; validate non-ServiceNow orchestration, licensing and robot depth","SRC-009"],
 ["Amazon Bedrock","AWS-native generative and agentic AI","AWS estates building custom governed AI applications",1,4,5,4,2,5,5,3,5,2,5,2,5,2,2,2,2,2,"Model choice, agents, knowledge bases, guardrails, IAM/VPC integration and AWS operations","Not a full RPA suite; requires engineering, cloud architecture, FinOps and separate UI automation","SRC-010; SRC-011; SRC-012"],
 ["Google Vertex AI","Google Cloud AI development platform","GCP / BigQuery / Workspace estates building production AI and agents",1,4,5,4,2,5,5,3,5,2,5,2,2,5,2,2,2,2,"Model Garden, Agent Engine, evaluation, monitoring, IAM and Google Cloud data/ML integration","Not a full RPA suite; confirm feature launch stage, regions, security controls and engineering capacity","SRC-013; SRC-014"],
 ["IBM watsonx Orchestrate","Open agent orchestration and governance","IBM/Red Hat or multi-model estates needing a governed agent control plane",2,4,5,3,2,5,5,4,5,4,4,3,3,3,3,3,3,5,"Agent builder, multi-agent orchestration, model routing, governed catalogue, control plane and enterprise connectors","Validate RPA depth, deployment edition, preview features, connector specifics and commercial model","SRC-015; SRC-016"],
 ["OpenAI API Platform","Developer-first AI and agents","Organizations building custom AI products with strong engineering and governance",1,4,5,4,1,4,4,2,5,2,5,3,3,3,3,3,3,3,"Models, agent tooling, tool use, evaluations, guardrails patterns and developer APIs","Not a full RPA suite; client must supply integration, identity, hosting architecture, monitoring and governance controls","SRC-017"]
];catalog.getRange("A5:X13").values=toolRows;catalog.getRange("A5:X13").format=bodyFmt;catalog.getRange("D5:U13").format.numberFormat="0";scoreCF(catalog.getRange("D5:U13"));addTable(catalog,"A4:X13","ToolFeatureCatalogue");widths(catalog,{A:30,B:28,C:38,D:12,E:14,F:12,G:12,H:12,I:13,J:13,K:13,L:12,M:12,N:14,O:12,P:14,Q:17,R:17,S:12,T:12,U:13,V:44,W:45,X:24});setup(catalog);catalog.freezePanes.freezeColumns(3);

title(score,"Tool Scorecard & Shortlist","Calculated recommendation = weighted capability score plus client-platform alignment. Confirm mandatory requirements and proof-of-capability before selection.","Q");score.getRange("A4:Q4").values=[["Tool / Platform","RPA","Workflow","AI Agents","Documents","Discovery","Governance","Deployment","Operations","Skills","Commercial","Portability","Platform Alignment","Capability Score","Overall Score","Rank","Decision / Conditions"]];score.getRange("A4:Q4").format=headFmt;
for(let i=0;i<toolRows.length;i++){
 const r=5+i,cr=5+i;score.getRange(`A${r}`).formulas=[[`='Tool Catalogue'!A${cr}`]];
 score.getRange(`B${r}:L${r}`).formulas=[[`='Tool Catalogue'!D${cr}`,`='Tool Catalogue'!E${cr}`,`='Tool Catalogue'!F${cr}`,`='Tool Catalogue'!G${cr}`,`='Tool Catalogue'!H${cr}`,`='Tool Catalogue'!I${cr}`,`='Tool Catalogue'!J${cr}`,`='Tool Catalogue'!K${cr}`,`='Resource Capacity'!K${cr}`,`=3`,`=3`]];
 score.getRange(`M${r}`).formulas=[[`=ROUND(('Tool Catalogue'!N${cr}*'Client Platform Landscape'!$B$5+'Tool Catalogue'!O${cr}*'Client Platform Landscape'!$B$6+'Tool Catalogue'!P${cr}*'Client Platform Landscape'!$B$7+'Tool Catalogue'!Q${cr}*'Client Platform Landscape'!$B$8+'Tool Catalogue'!R${cr}*'Client Platform Landscape'!$B$9+'Tool Catalogue'!S${cr}*'Client Platform Landscape'!$B$10+'Tool Catalogue'!T${cr}*'Client Platform Landscape'!$B$11+'Tool Catalogue'!U${cr}*'Client Platform Landscape'!$B$12)/MAX(1,SUM('Client Platform Landscape'!$B$5:$B$12)),1)`]];
 score.getRange(`N${r}`).formulas=[[`=ROUND((B${r}*'Selection Criteria'!$B$5+C${r}*'Selection Criteria'!$B$6+D${r}*'Selection Criteria'!$B$7+E${r}*'Selection Criteria'!$B$8+F${r}*'Selection Criteria'!$B$9+G${r}*'Selection Criteria'!$B$11+H${r}*'Selection Criteria'!$B$12+I${r}*'Selection Criteria'!$B$13+J${r}*'Selection Criteria'!$B$14+K${r}*'Selection Criteria'!$B$15+L${r}*'Selection Criteria'!$B$16)*20,1)`]];
 score.getRange(`O${r}`).formulas=[[`=ROUND(N${r}+M${r}*20*'Selection Criteria'!$B$17,1)`]];score.getRange(`P${r}`).formulas=[[`=RANK(O${r},$O$5:$O$13,0)`]];score.getRange(`Q${r}`).formulas=[[`=IF(J${r}<2.5,"RESOURCE GATE — build capacity or select an alternative",IF(J${r}<3.5,"Resource remediation plan required","Capacity appears viable — validate named resources"))`]];
}
score.getRange("A5:Q13").format=bodyFmt;score.getRange("B5:M13").format.numberFormat="0.0";score.getRange("N5:O13").format.numberFormat="0.0";scoreCF(score.getRange("O5:O13"));score.getRange("Q5:Q13").format={fill:C.cream,font:{bold:true,color:C.navy,size:9},wrapText:true};addTable(score,"A4:Q13","ToolShortlistScorecard");widths(score,{A:32,B:10,C:11,D:11,E:11,F:11,G:12,H:12,I:12,J:11,K:12,L:11,M:18,N:16,O:14,P:9,Q:48});setup(score);score.freezePanes.freezeColumns(1);

title(decision,"Tool Selection Decision Record","Document the evidence and rationale for the selected platform. A recommendation is incomplete without conditions, ownership and an exit strategy.","H");decision.getRange("A4:H4").values=[["Decision Field","Entry","Evidence / Link","Approver","Date","Condition / Action","Owner","Due Date"]];decision.getRange("A4:H4").format=headFmt;const fields=["Use case / portfolio scope","Shortlisted tools","Selected tool(s)","Why it fits the client platform","Mandatory capability validation","Resource availability and capacity outcome","Security / privacy / regulatory outcome","Architecture and integration outcome","Three-year TCO outcome","Pilot results","Key limitations accepted","Conditions before production","Portability / exit strategy","Dissent or alternative view","Approval decision","Next review trigger"];
for(let i=0;i<fields.length;i++){const r=5+i;decision.getRange(`A${r}`).values=[[fields[i]]];decision.getRange(`B${r}:H${r}`).format=inputFmt;}decision.getRange("E5:E20").format.numberFormat="yyyy-mm-dd";decision.getRange("H5:H20").format.numberFormat="yyyy-mm-dd";widths(decision,{A:34,B:40,C:40,D:22,E:15,F:42,G:22,H:15});setup(decision);

title(sources,"Official Product Sources","Feature statements should be revalidated during procurement because product names, editions, regions, licensing and release status change.","F");sources.getRange("A4:F4").values=[["Source ID","Vendor / Product","Official URL","Capabilities supported","Checked","Procurement note"]];sources.getRange("A4:F4").format=headFmt;const srcRows=[
 ["SRC-001","Microsoft Power Automate desktop flows","https://learn.microsoft.com/en-us/power-automate/desktop-flows/trigger-desktop-flows","Desktop flows, machines, attended/unattended execution and cloud-flow invocation","2026-07-19","Confirm licensing, regions and run capacity"],
 ["SRC-002","Microsoft Copilot Studio","https://learn.microsoft.com/en-us/microsoft-copilot-studio/","Agents, knowledge, tools, connectors, evaluations, analytics and channels","2026-07-19","Validate feature release status and tenant configuration"],
 ["SRC-003","Copilot Studio governance","https://learn.microsoft.com/en-gb/microsoft-copilot-studio/security-and-governance","Data policies, environments, publishing, residency and governance controls","2026-07-19","Map controls to client Power Platform strategy"],
 ["SRC-004","UiPath Document Understanding","https://docs.uipath.com/document-understanding/automation-cloud/latest/user-guide/about-document-understanding","RPA + AI document extraction, interpretation and human validation","2026-07-19","Validate deployment type and document accuracy"],
 ["SRC-005","UiPath Process Mining","https://docs.uipath.com/process-mining/automation-cloud/latest/user-guide/process-mining-architecture-overview","Process data extraction, transformation and dashboards","2026-07-19","Confirm source connectors and data-handling design"],
 ["SRC-006","Automation Anywhere 360","https://docs.automationanywhere.com/r/cloud-automation-anywhere-enterprise-overview","RPA, AI agents, APIs, orchestration, IDP, analytics and deployment options","2026-07-19","Confirm edition, region and license availability"],
 ["SRC-007","Automation Anywhere Process Discovery","https://docs.automationanywhere.com/r/automation-360/process-discovery-overview","Process capture, analysis, ROI comparison and PDD output","2026-07-19","Assess employee privacy and capture controls"],
 ["SRC-008","SS&C Blue Prism documentation","https://documentation.blueprism.com/","Enterprise RPA platform documentation and release-specific capabilities","2026-07-19","Validate selected version and AI roadmap"],
 ["SRC-009","ServiceNow automation","https://www.servicenow.com/products/automation-engine.html","IntegrationHub, RPA Hub, Automation Center and Document Intelligence","2026-07-19","Product now presented within Workflow Data Fabric; confirm packaging"],
 ["SRC-010","Amazon Bedrock Agents","https://docs.aws.amazon.com/bedrock/latest/userguide/agents-how.html","Agent orchestration, actions, knowledge bases and prompt customization","2026-07-19","Confirm models and regional availability"],
 ["SRC-011","Amazon Bedrock Knowledge Bases","https://docs.aws.amazon.com/bedrock/latest/userguide/knowledge-base.html","Managed RAG over enterprise data","2026-07-19","Validate vector store, ingestion and security architecture"],
 ["SRC-012","Amazon Bedrock Guardrails","https://docs.aws.amazon.com/bedrock/latest/userguide/guardrails.html","Content, topic, sensitive-information and safety controls","2026-07-19","Guardrails complement—not replace—application controls"],
 ["SRC-013","Google Vertex AI generative AI","https://docs.cloud.google.com/vertex-ai/generative-ai/docs","Models, agents, evaluation, enterprise security and Model Garden","2026-07-19","Confirm launch stage, model and region"],
 ["SRC-014","Vertex AI Agent Engine","https://cloud.google.com/vertex-ai/generative-ai/docs/reasoning-engine/overview","Managed agent runtime, frameworks, observability and evaluation","2026-07-19","Validate security-control support for selected configuration"],
 ["SRC-015","IBM watsonx Orchestrate","https://www.ibm.com/products/watsonx-orchestrate/multi-agent-orchestration","Multi-agent orchestration, model routing, monitoring and control plane","2026-07-19","Confirm edition and feature availability"],
 ["SRC-016","IBM agent catalogue","https://www.ibm.com/products/watsonx-orchestrate/agent-catalog","Governed agent/tool catalogue, RBAC and lifecycle management","2026-07-19","Validate integrations and partner agents"],
 ["SRC-017","OpenAI API platform docs","https://platform.openai.com/docs/","Models, agents, tools, evaluations and developer platform capabilities","2026-07-19","Client must design surrounding enterprise controls and integrations"]
];sources.getRange(`A5:F${4+srcRows.length}`).values=srcRows;sources.getRange(`A5:F${4+srcRows.length}`).format=bodyFmt;sources.getRange(`E5:E${4+srcRows.length}`).format.numberFormat="yyyy-mm-dd";addTable(sources,`A4:F${4+srcRows.length}`,"OfficialProductSources");widths(sources,{A:14,B:30,C:72,D:48,E:16,F:42});setup(sources);

await wb2.comments.setSelf({displayName:"Ratheesh Technology Ltd."});
const out2=await SpreadsheetFile.exportXlsx(wb2);await out2.save(fileURLToPath(new URL("AI_RPA_Platform_Aligned_Tool_Selection.xlsx",outDir)));

// Compact verification and previews for every sheet.
for(const [wb,label] of [[wb1,"priority"],[wb2,"tools"]]){
 const err=await wb.inspect({kind:"match",searchTerm:"#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A",options:{useRegex:true,maxResults:100},summary:`${label} formula scan`});
 console.log(label,err.ndjson);
 for(const sh of wb.worksheets.items){
  const preview=await wb.render({sheetName:sh.name,autoCrop:"all",scale:0.75,format:"png"});
  await fs.writeFile(new URL(`${label}-${sh.name.replace(/[^a-z0-9]+/gi,"-").toLowerCase()}.png`,outDir),new Uint8Array(await preview.arrayBuffer()));
 }
}
