const views={
 dashboard:{crumb:'OPERATIONS / OVERVIEW',title:'Commission operations',sub:'Monitor governed processing, exceptions, and approvals across the incentive lifecycle.'},
 processing:{crumb:'OPERATIONS / PROCESSING',title:'Process commissions',sub:'Run a governed request and inspect every decision boundary.'},
 dealers:{crumb:'OPERATIONS / DEALERS',title:'Dealer 360',sub:'Review performance, transaction, commission, and payment history.'},
 transactions:{crumb:'OPERATIONS / TRANSACTIONS',title:'Transactions',sub:'Investigate current, historical, adjusted, and cancelled business.'},
 exceptions:{crumb:'OPERATIONS / EXCEPTIONS',title:'Exception workbench',sub:'Resolve duplicates, anomalies, data-quality issues, and calculation mismatches.'},
 approvals:{crumb:'OPERATIONS / APPROVALS',title:'Approval centre',sub:'Apply human judgment with role and segregation-of-duties controls.'},
 rag:{crumb:'KNOWLEDGE / SOP & RAG',title:'SOP knowledge governance',sub:'Control document privacy review, activation, chunking, and retrieval evidence.'},
 governance:{crumb:'CONTROL PLANE / GOVERNANCE',title:'AI governance registry',sub:'Manage data contracts, sensitive-data policy, controls, and approved models.'},
 security:{crumb:'CONTROL PLANE / SECURITY',title:'Access & duties',sub:'Review users, roles, permissions, and incompatible responsibilities.'},
 audit:{crumb:'EVIDENCE / AUDIT',title:'Immutable evidence ledger',sub:'Trace data exposure, retrieval, calculations, decisions, and user activity.'}
};
const rows={
 dealers:[['DLR-1042','Priya Shah','Platinum','$428,760','Eligible'],['DLR-1088','Marcus Chen','Gold','$312,480','Review'],['DLR-1127','Elena Rossi','Silver','$187,220','Eligible'],['DLR-1164','Noah Williams','Gold','$295,940','Hold']],
 transactions:[['TXN-846291','2026-09-09','Mortgage','$640,000','Calculated'],['TXN-846275','2026-09-09','Investment','$185,000','Review'],['TXN-846244','2026-09-08','Personal lending','$84,500','Blocked'],['TXN-846201','2026-09-08','Mortgage','$515,000','Approved']],
 exceptions:[['EXC-2041','Calculation mismatch','TXN-846244','Critical','Blocked'],['EXC-2038','Potential duplicate','TXN-846219','High','Review'],['EXC-2034','Historical anomaly','DLR-1088','Medium','Review'],['EXC-2029','Data quality','TXN-846187','High','Blocked']],
 approvals:[['APR-1192','Commission','$18,420','S. Ibrahim','Review'],['APR-1190','Exception override','$15,800','J. Park','Review'],['APR-1188','Commission','$7,960','L. Bernard','Review']],
 security:[['USR-012','Alex Morgan','Operations Analyst','Submitter','Active'],['USR-018','Sam Ibrahim','Commission Approver','Approver','Active'],['USR-024','Jordan Park','Process Owner','Exception owner','Active'],['USR-031','Taylor Kim','Privacy Reviewer','Document reviewer','Active']],
 audit:[['TRACE-7F4A92','Commission calculated','TXN-846291','14:42:18','Sealed'],['TRACE-7F49E1','LLM invocation blocked','TXN-846244','14:39:05','Sealed'],['TRACE-7F47C0','Duplicate routed','TXN-846219','14:35:44','Sealed'],['TRACE-7F452A','SOP activation denied','SOP-001-v3','14:28:11','Sealed']]
};
const pipeline=['Identity','Data contract','PII gateway','RAG retrieval','AI interpretation','Calculation','Controls','Decision'];
document.querySelector('#pipeline').innerHTML=pipeline.map((p,i)=>`<div class="pipe-step"><div class="pipe-node"><i>${i<7?'✓':'$'}</i><span>${p}</span></div></div>`).join('');
const scenarioNames=['Standard commission calculation','Volume threshold crossing','Premium + campaign stacking','Exact / potential duplicate','Early cancellation & clawback','Compliance hold','Split commission','SOP effective date','Prior-period correction','Complex end-to-end batch'];
function statusClass(v){return /block|critical|hold/i.test(v)?'blocked':/review|medium|high/i.test(v)?'review':/seal|active|eligible|approved|calculated/i.test(v)?'':'info'}
function table(headers,data){return `<article class="card table-card wide"><div class="toolbar"><h2>Operational records</h2><button class="filter">Status: All</button><button class="secondary">Download</button></div><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${data.map(r=>`<tr>${r.map((c,i)=>`<td>${i===r.length-1?`<span class="status ${statusClass(c)}">${c}</span>`:c}</td>`).join('')}</tr>`).join('')}</tbody></table></article>`}
function render(view){
 const el=document.querySelector(`#${view}`); if(el.dataset.ready)return;
 if(view==='processing') el.innerHTML=`<div class="workspace-grid"><article class="card feature-card"><p class="eyebrow">NEW REQUEST</p><h2>Governed processing pipeline</h2><p>Select a mandatory acceptance scenario. The demonstration applies the active data contract, retrieves approved SOP chunks, calculates deterministically, and produces sealed evidence.</p><div class="scenario-grid">${scenarioNames.map((s,i)=>`<button class="scenario"><strong>SCN-${String(i+1).padStart(2,'0')}</strong><small>${s}</small><span class="status ${i===3||i===5?'review':''}">${i===3||i===5?'HITL expected':'Ready'}</span></button>`).join('')}</div></article><article class="card feature-card"><p class="eyebrow">EXECUTION GUARANTEE</p><h2>Interpret, validate, control</h2><div class="steps">${['Trusted security context established','Active AI Data Contract enforced','Sensitive fields tokenized or blocked','Approved SOP sections retrieved','Structured rules interpreted by Gemini','Financial result calculated in code','Controls and SoD policy evaluated','Decision evidence sealed'].map((s,i)=>`<div class="step"><b>${i+1}</b><div><strong>${s}</strong><small>${i===4?'No executable code or payment authority':i===5?'Decimal arithmetic; independently reproducible':'Evidence attached to trace'}</small></div></div>`).join('')}</div></article></div>`;
 else if(view==='rag') el.innerHTML=`<div class="workspace-grid"><article class="card feature-card"><p class="eyebrow">DOCUMENT LIFECYCLE</p><h2>SOP-INCENTIVE-001-v3</h2><p>The uploaded draft contains one critical SIN finding. Retrieval is fail-closed until a privacy reviewer resolves the finding and a policy owner approves the sanitized representation.</p><div class="steps">${['Uploaded','Scanning complete','PII review required','Privacy approval','RAG-safe representation','Chunk & embed','Vector validation','Policy owner approval','Active'].map((s,i)=>`<div class="step"><b>${i<3?'✓':i===2?'!':i+1}</b><div><strong>${s}</strong><small>${i===2?'BLOCKED · SIN in worked example on page 14':i<2?'Evidence recorded':'Pending prerequisite'}</small></div></div>`).join('')}</div></article><article class="card table-card"><div class="toolbar"><h2>SOP version registry</h2><button class="primary">Upload SOP</button></div><table><thead><tr><th>Version</th><th>Effective</th><th>Chunks</th><th>Status</th></tr></thead><tbody><tr><td>INC-001 v2</td><td>2026-07-01 →</td><td>47</td><td><span class="status">Active</span></td></tr><tr><td>INC-001 v1</td><td>2025-01-01 → 2026-06-30</td><td>43</td><td><span class="status info">Superseded</span></td></tr><tr><td>INC-001 v3</td><td>Draft</td><td>—</td><td><span class="status blocked">PII blocked</span></td></tr></tbody></table></article></div>`;
 else if(view==='governance') el.innerHTML=`<div class="workspace-grid">${table(['Automation','Data contract','Model','Controls','Status'],[['Incentive calculation','ADC-INC-04 v3','Gemini 2.5 Flash','14','Active'],['Clawback assessment','ADC-CLW-02 v2','Gemini 2.5 Flash','11','Active'],['Campaign eligibility','ADC-CAM-01 v1','Gemini 2.5 Flash','9','Draft']])}<article class="card feature-card"><p class="eyebrow">FIELD POLICY</p><h2>AI Data Contract · ADC-INC-04 v3</h2><div class="steps">${[['CUSTOMER_NAME','TOKENIZE'],['DEALER_ID','ALLOW'],['FINANCIAL_AMOUNT','ALLOW'],['BANK_ACCOUNT','BLOCK'],['CUSTOMER_SEGMENT','DERIVE'],['UNCLASSIFIED_*','BLOCK']].map((x,i)=>`<div class="step"><b>${i+1}</b><div><strong>${x[0]}</strong><small>${x[1]} · evidence required</small></div></div>`).join('')}</div></article></div>`;
 else {const heads={dealers:['Dealer','Name','Tier','YTD commission','Status'],transactions:['Transaction','Date','Product','Principal','Status'],exceptions:['Exception','Type','Subject','Severity','Status'],approvals:['Approval','Type','Exposure','Submitted by','Status'],security:['User','Name','Role','Duty','Status'],audit:['Trace','Event','Subject','Time','Integrity']}[view]; el.innerHTML=table(heads,rows[view]);}
 el.dataset.ready='1'; el.querySelectorAll('.scenario').forEach(b=>b.onclick=()=>runScenario(b));
}
function switchView(view){if(!views[view])return;document.querySelectorAll('.view').forEach(v=>v.classList.remove('active-view'));document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===view));if(view!=='dashboard')render(view);document.querySelector(`#${view}`).classList.add('active-view');document.querySelector('#breadcrumb').textContent=views[view].crumb;document.querySelector('#pageTitle').textContent=views[view].title;document.querySelector('#pageSubtitle').textContent=views[view].sub;history.replaceState(null,'',`#${view}`);window.scrollTo({top:0,behavior:'smooth'})}
document.addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b)switchView(b.dataset.view)});
function runScenario(btn){btn.querySelector('.status').textContent='Running…';setTimeout(()=>{btn.querySelector('.status').textContent=btn.textContent.includes('duplicate')||btn.textContent.includes('Compliance')?'Routed to HITL':'Validated';toast('Execution complete · evidence sealed')},700)}
const evidence={"Automation":"INCENTIVE-CALC v4.2","SOP / version":"SOP-INCENTIVE-001 v2","Data contract":"ADC-INC-04 v3","Model":"Gemini 2.5 Flash","Retrieved chunks":"4.2 · 7.1 · 11.3","Calculation":"$640,000 × 0.42% × 1.06 = $2,847.60","Controls":"14 passed · 0 failed","Approval":"Not required","Final decision":"CALCULATED — payment pending","Evidence hash":"sha256:8ab4…d921"};
document.querySelector('#traceDetail').innerHTML=`<div class="evidence-grid">${Object.entries(evidence).map(([k,v])=>`<div><span>${k}</span><strong>${v}</strong></div>`).join('')}</div>`;
document.querySelector('#inspectTrace').onclick=()=>document.querySelector('#traceDialog').showModal();document.querySelector('#evidenceBtn').onclick=()=>toast('Evidence package prepared for TRACE-7F4A92');
document.addEventListener('click',event=>{const button=event.target.closest('.filter,.toolbar .secondary,.toolbar .primary,.icon-btn');if(button&&!button.closest('dialog'))toast(`${button.textContent.trim()||button.getAttribute('aria-label')} demonstrated with synthetic data`)});
function toast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
switchView(location.hash.slice(1)||'dashboard');
