const BASE='/enterprise-architecture';
const solutions={banking:{id:'AUTO-CBA-001',name:'Customer Banking Agent',category:'Agentic Customer Service',architecture:'Gemini · ADK · MCP · FastAPI',contract:'ADC-CBA v1.3',rag:'Optional',controls:'CTRL-CBA-07',path:`${BASE}/banking-agent-demo/`},commission:{id:'AUTO-ICP-002',name:'Incentive & Commission Processing',category:'Governed RAG / Financial Processing',architecture:'Gemini · RAG · Deterministic Calculation · HITL',contract:'ADC-INC-04 v3',rag:'Prototype / partial',controls:'CTRL-INC-14',path:`${BASE}/incentive-commission-demo/`}};
const pageMeta={
 overview:['AI OPERATIONS / OVERVIEW','Enterprise AI control centre','One operating view across customer service and governed financial processing.'],
 requests:['OPERATIONS / REQUESTS','AI request operations','Monitor requests across registered solutions. Synthetic demonstration records are clearly identified.'],
 exceptions:['OPERATIONS / EXCEPTIONS','Enterprise exception queue','Prioritize control failures and route cases to accountable owners.'],
 approvals:['OPERATIONS / APPROVALS','Approval workbench','Review human decisions separately from controlled execution.'],
 registry:['GOVERNANCE / AUTOMATION REGISTRY','Automation registry','Authoritative operating profile for every registered AI solution.'],
 contracts:['GOVERNANCE / AI DATA CONTRACTS','AI Data Contracts','Compare approved field handling and runtime boundaries across solutions.'],
 pii:['GOVERNANCE / PII & SENSITIVE DATA','PII & Sensitive Data Library','Review shared classifications and solution-specific handling decisions.'],
 rag:['GOVERNANCE / RAG','RAG governance','See where retrieval is allowed, required, or unavailable—and which controls apply.'],
 controls:['GOVERNANCE / CONTROLS','Control library','Map preventative, detective, and approval controls to each automation.'],
 models:['GOVERNANCE / MODELS','Model registry','Approved model profiles and permitted purposes by automation.'],
 policies:['GOVERNANCE / APPROVAL POLICIES','Approval policies','Human decision rules, thresholds, and segregation requirements.'],
 security:['SECURITY / ACCESS & DUTIES','Security administration','Users, roles, permissions, and incompatible duties across AI operations.'],
 audit:['AUDIT / EVIDENCE','Evidence explorer','Filter synthetic cross-solution evidence without implying live production activity.']
};
const metrics=[['Active AI Solutions','2','Both governance-enabled','good'],['AI Requests Today','1,284','Synthetic operating total',''],['Pending Approvals','3','$42,180 exposure',''],['Governance Exceptions','7','2 payment-blocking','risk'],['PII Events','18','17 tokenized · 1 blocked',''],['Blocked AI Requests','4','Fail-closed decisions','risk'],['RAG Documents Active','2','Commission SOP v1 / v2',''],['Control Failures','6','Across 1,284 requests','risk']];
document.querySelector('#metrics').innerHTML=metrics.map(x=>`<article class="metric"><span>${x[0]}</span><b>${x[1]}</b><small class="${x[3]}">${x[2]}</small></article>`).join('');
document.querySelector('#solutionCards').innerHTML=Object.entries(solutions).map(([k,s])=>`<article class="solution-card"><div class="solution-main"><span class="solution-icon">${k==='banking'?'◎':'▦'}</span><div><b>${s.name}</b><small>${s.category} · ${s.architecture}</small></div><span class="status">ACTIVE</span></div><div class="solution-meta"><div><small>AUTOMATION</small><b>${s.id}</b></div><div><small>DATA CONTRACT</small><b>${s.contract} · ACTIVE</b></div><div><small>RAG</small><b>${s.rag}</b></div><div><small>GOVERNANCE</small><b>ENABLED</b></div></div><div class="solution-actions"><button data-view="${k}">Open solution workspace</button><button data-view="registry">View governance profile</button></div></article>`).join('');
const attention=[['warn','Commission approval','AUTO-ICP-002 · 3 requests','$42,180'],['block','Calculation mismatch','AUTO-ICP-002 · payment blocked','2'],['warn','Approval threshold','AUTO-CBA-001 · banker review','1'],['block','Sensitive field blocked','AUTO-ICP-002 · fail closed','1']];
document.querySelector('#attentionRows').innerHTML=attention.map(x=>`<div class="attention-row"><span class="event-icon ${x[0]}">${x[0]==='block'?'!':'✓'}</span><div><b>${x[1]}</b><small>${x[2]}</small></div><span>${x[3]}</span></div>`).join('');
const headers=['Authentication','Data contract','PII policy','Model','Tools','RAG policy','Controls','Evidence'];
document.querySelector('#coverage').innerHTML=`<div class="coverage-row"><span>Solution</span>${headers.map(h=>`<span>${h}</span>`).join('')}</div>`+Object.values(solutions).map((s,i)=>`<div class="coverage-row"><b>${s.name}</b>${headers.map((h,j)=>`<span class="check ${j===5&&i===0?'optional':''}">${j===5&&i===0?'○':'✓'}</span>`).join('')}</div>`).join('');
const events=[['◎','Customer Banking Agent','Resource authorization passed · TRACE-CBA-8D12','10:42'],['▦','Commission Processing','Deterministic calculation completed · TRACE-7F4A92','10:38'],['!','Commission Processing','Calculation variance blocked · TRACE-7F49E1','10:31'],['◇','Customer Banking Agent','Approval threshold reached · TRACE-CBA-8C98','10:26']];
document.querySelector('#eventFeed').innerHTML=events.map((x,i)=>`<div class="event-row"><span class="event-icon ${i===2?'block':''}">${x[0]}</span><div><b>${x[1]}</b><small>${x[2]}</small></div><small>${x[3]}</small></div>`).join('');

const registry=[['AUTO-CBA-001','Customer Banking Agent','Retail Banking','AI Platform','Agentic service','Gemini 2.5 Flash','High','ADC-CBA v1.3','Optional','RAG-CBA v1','CTRL-CBA-07','SEC-CUST-02','ACTIVE','2026-08-14','2026-09-09 10:42'],['AUTO-ICP-002','Incentive & Commission Processing','Sales Compensation','AI Platform','Governed financial','Gemini 2.5 Flash','High','ADC-INC-04 v3','Required','RAG-INC v2','CTRL-INC-14','SEC-OPS-04','ACTIVE*','2026-09-01','2026-09-09 10:38']];
const requests=[['REQ-84821','Customer Banking Agent','Balance + transactions','Alex Morgan','PASSED','10:42'],['REQ-84820','Commission Processing','Calculate TXN-846291','Alex Morgan','CALCULATED','10:38'],['REQ-84819','Commission Processing','Calculate TXN-846244','Alex Morgan','BLOCKED','10:31'],['REQ-84818','Customer Banking Agent','Credit limit request','Riley Chen','PENDING APPROVAL','10:26']];
const exceptions=[['EXC-2041','Commission Processing','Calculation mismatch','Critical','BLOCKED','Commission Manager'],['EXC-2038','Commission Processing','Potential duplicate','High','REVIEW','Process Owner'],['EXC-CBA-018','Customer Banking Agent','Non-enumeration attempt','High','BLOCKED','Security Reviewer'],['EXC-2034','Commission Processing','Historical anomaly','Medium','REVIEW','Commission Manager']];
const approvals=[['APR-1192','Commission Processing','Commission','$18,420','PENDING','S. Ibrahim'],['APR-CBA-031','Customer Banking Agent','Credit limit','$30,000','PENDING','Banker'],['APR-1190','Commission Processing','Exception override','$15,800','PENDING','J. Park']];
function tag(v){const c=/BLOCK|CRITICAL/.test(v)?'block':/PENDING|REVIEW|HIGH|PARTIAL|REQUIRED/.test(v)?'warn':'';return `<span class="tag ${c}">${v}</span>`}
function table(headers,rows){return `<article class="panel wide"><div class="panel-head"><div><p>CROSS-SOLUTION VIEW</p><h2>Operational records</h2></div><span class="synthetic">SYNTHETIC DEMO DATA</span></div><div style="overflow:auto"><table class="data-table"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${/ACTIVE|PASSED|CALCULATED|BLOCKED|PENDING|REVIEW|Critical|High/.test(c)?tag(c):c}</td>`).join('')}</tr>`).join('')}</tbody></table></div></article>`}
function rule(title,detail,handling='ACTIVE'){return `<div class="rule"><div><b>${title}</b><small>${detail}</small></div><span class="pill ${handling==='BLOCK'?'block':''}">${handling}</span></div>`}
function render(view){const d=document.querySelector('#dynamicView');
 if(view==='registry')d.innerHTML=table(['Automation ID','Name','Business Owner','Technical Owner','Type','Model','Risk','Data Contract','RAG','RAG Policy','Control Set','Security','Status','Last Approval','Last Execution'],registry);
 else if(view==='requests')d.innerHTML=table(['Request','Automation','Intent','User','Result','Time'],requests);
 else if(view==='exceptions')d.innerHTML=table(['Exception','Automation','Control result','Severity','Status','Owner'],exceptions);
 else if(view==='approvals')d.innerHTML=table(['Approval','Automation','Type','Exposure','Status','Assigned to'],approvals);
 else if(view==='contracts')d.innerHTML=`<div class="content-grid"><article class="info-panel"><p class="eyebrow">AUTO-CBA-001 · ADC-CBA v1.3</p><h2 class="section-title">Customer Banking Agent</h2><p>Customer-service fields are minimized before model use. Account and identity values remain governed by trusted application context.</p><div class="rule-list">${rule('customer_name','Typed identity token','TOKENIZE')}${rule('account_number','Account-scoped token','TOKENIZE')}${rule('balance','Required customer-service value','ALLOW')}${rule('SIN','Never permitted for model use','BLOCK')}</div></article><article class="info-panel"><p class="eyebrow">AUTO-ICP-002 · ADC-INC-04 v3</p><h2 class="section-title">Commission Processing</h2><p>Calculation values remain available while direct identity and restricted fields are transformed or blocked.</p><div class="rule-list">${rule('dealer_name','Typed dealer token','TOKENIZE')}${rule('customer_name','Typed person token','TOKENIZE')}${rule('transaction_amount','Required calculation value','ALLOW')}${rule('historical_volume','Required threshold input','ALLOW')}${rule('SIN','Never permitted for model use','BLOCK')}</div></article></div>`;
 else if(view==='pii')d.innerHTML=`<div class="content-grid"><article class="panel wide"><div class="panel-head"><div><p>SHARED CLASSIFICATION</p><h2>Sensitive data decision matrix</h2></div><span>Versioned policies</span></div>${table(['Category','Classification','Default','Banking Agent','Commission Processing'],[['PERSON_NAME','PII','TOKENIZE','TOKENIZE','TOKENIZE'],['ACCOUNT_NUMBER','Restricted','TOKENIZE','TOKENIZE','TOKENIZE'],['FINANCIAL_AMOUNT','Confidential','ALLOW','ALLOW','ALLOW'],['HISTORICAL_VOLUME','Confidential','ALLOW','N/A','ALLOW'],['SIN','Restricted','BLOCK','BLOCK','BLOCK'],['AUTH_SECRET','Restricted','BLOCK','BLOCK','BLOCK']]).replace('<article class="panel wide">','').replace(/<\/article>$/,'')}</article></div>`;
 else if(view==='rag')d.innerHTML=`<div class="content-grid"><article class="info-panel"><p class="eyebrow">CUSTOMER BANKING AGENT</p><h2 class="section-title">Optional policy retrieval</h2><p>RAG is not required for account data access. It may be used only for approved policy knowledge, with customer resources retrieved through authorized tools.</p><div class="rule-list">${rule('RAG mode','Optional / policy knowledge','LIMITED')}${rule('Customer data','Never sourced from vector index','BLOCK')}${rule('Activation','Privacy and policy approval required','REQUIRED')}</div></article><article class="info-panel"><p class="eyebrow">COMMISSION PROCESSING</p><h2 class="section-title">Mandatory SOP retrieval</h2><p>Governed SOP sections are required for rule interpretation. Current Phase 2 audit classifies cloud retrieval as not implemented; the interface does not represent it as live.</p><div class="rule-list">${rule('RAG mode','Required for SOP interpretation','REQUIRED')}${rule('Document control','PII scan before activation','REQUIRED')}${rule('Current implementation','Local prototype; Vectorize not connected','PARTIAL')}</div></article></div>`;
 else if(view==='controls')d.innerHTML=table(['Control ID','Control','Customer Banking','Commission','Type','Failure action'],[['CTRL-AUTH-01','Resource Authorization','Required','Required','Preventative','BLOCK'],['CTRL-ENUM-02','Non-Enumeration','Required','—','Preventative','BLOCK'],['CTRL-MFA-03','MFA Requirement','Required','Required','Preventative','BLOCK'],['CTRL-APR-04','Approval Threshold','Required','Required','Approval','HOLD'],['CTRL-DUP-01','Duplicate Detection','—','Required','Detective','BLOCK / REVIEW'],['CTRL-ANM-02','Historical Anomaly','—','Required','Detective','HOLD'],['CTRL-CALC-03','Calculation Variance','—','Required','Detective','BLOCK'],['CTRL-COMP-04','Compliance Hold','—','Required','Preventative','HOLD'],['CTRL-SOP-05','SOP Version Resolution','—','Required','Preventative','BLOCK'],['CTRL-RAG-06','RAG Approval','Optional','Required','Preventative','BLOCK']]);
 else if(view==='models')d.innerHTML=table(['Model','Provider','Approved purpose','Automations','Data class','Status'],[['Gemini 2.5 Flash','Google','Intent and structured rule interpretation','CBA-001 · ICP-002','Tokenized / approved','APPROVED'],['Deterministic Engine v1','RR Bank','Financial calculation','ICP-002','Confidential financial','ACTIVE']]);
 else if(view==='policies')d.innerHTML=table(['Policy','Applies to','Trigger','Required role','SoD','State'],[['APR-CBA-02','Customer Banking','Credit limit threshold','Banker','Requester ≠ approver','ACTIVE'],['APR-INC-04','Commission','Exception or amount threshold','Incentive Manager','Processor ≠ approver','ACTIVE'],['APR-RAG-02','Commission RAG','Document activation','Privacy + Policy Owner','Uploader ≠ approver','ACTIVE']]);
 else if(view==='security')d.innerHTML=`<div class="content-grid">${table(['User','Role','Solution scope','Key permissions','Status'],[['Alex Morgan','PROCESSOR','Both','Submit · View evidence','ACTIVE'],['Sam Ibrahim','INCENTIVE_MANAGER','Commission','Approve commission','ACTIVE'],['Jordan Park','POLICY_OWNER','Both','Approve policy','ACTIVE'],['Taylor Kim','PRIVACY_OFFICER','Both','Review findings','ACTIVE'],['Morgan Lee','SECURITY_REVIEWER','Both','Review security events','ACTIVE']])}<article class="info-panel wide"><p class="eyebrow">SEGREGATION OF DUTIES</p><h2 class="section-title">Incompatible duty rules</h2><div class="rule-list">${rule('Submitter → Approver','Same user cannot submit and approve','DENY')}${rule('Document uploader → Privacy approver','Independent privacy review required','DENY')}${rule('Policy editor → Policy approver','Four-eyes activation','DENY')}</div></article></div>`;
 else if(view==='audit')d.innerHTML=`<div class="filters"><button>Automation: All</button><button>Trace ID</button><button>User: All</button><button>Date: Today</button><button>Control Result: All</button><button>PII Event</button><button>Approval Event</button><button>Security Event</button></div>${table(['Trace ID','Automation','User','Evidence type','Control result','Event','Time'],[['TRACE-CBA-8D12','Customer Banking Agent','Alex Morgan','AI Execution Trace','PASS','Authorized account read','10:42'],['TRACE-7F4A92','Commission Processing','Alex Morgan','Decision Evidence','PASS','Calculation completed','10:38'],['TRACE-7F49E1','Commission Processing','Alex Morgan','Control Evidence','FAIL','Calculation variance blocked','10:31'],['TRACE-CBA-8C98','Customer Banking Agent','Riley Chen','Approval Event','REVIEW','Banker approval required','10:26'],['TRACE-7F452A','Commission Processing','Taylor Kim','PII Event','FAIL','SOP activation denied','10:18']])}`;
}
function show(view){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active-view'));document.querySelectorAll('.nav-link').forEach(n=>n.classList.toggle('active',n.dataset.view===view));if(solutions[view]){const s=solutions[view];document.querySelector('#solutionTitle').textContent=s.name;document.querySelector('#solutionFrame').src=s.path;document.querySelector('#openSolution').href=s.path;document.querySelector('#solutionView').classList.add('active-view');document.querySelector('.page-head').hidden=true}else{document.querySelector('.page-head').hidden=false;const m=pageMeta[view]||pageMeta.overview;document.querySelector('#crumb').textContent=m[0];document.querySelector('#title').textContent=m[1];document.querySelector('#subtitle').textContent=m[2];if(view==='overview')document.querySelector('#overview').classList.add('active-view');else{render(view);document.querySelector('#dynamicView').classList.add('active-view')}}history.replaceState(null,'',`#${view}`);window.scrollTo(0,0)}
document.addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b)show(b.dataset.view);const filter=e.target.closest('.filters button');if(filter){filter.classList.toggle('active');toast(`${filter.textContent.trim()} filter updated`)}});document.querySelector('#refresh').onclick=()=>toast('Synthetic status refreshed · no live production events loaded');document.querySelector('.attention .plain').onclick=()=>show('exceptions');document.querySelector('.search').onclick=()=>{const query=window.prompt('Search this demonstration for a solution, request, control, or trace:');if(!query)return;const value=query.toLowerCase();if(value.includes('control'))show('controls');else if(value.includes('trace')||value.includes('evidence')||value.includes('audit'))show('audit');else if(value.includes('request'))show('requests');else if(value.includes('commission'))show('commission');else if(value.includes('bank'))show('banking');else{show('registry');toast(`Showing closest matches for “${query}”`)}};function toast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}show(location.hash.slice(1)||'overview');
