(()=>{
  const path=location.pathname;
  const profiles=path.includes('banking-agent-demo')?{
    title:'How to use the Banking AI demo',intro:'Run three guided requests and watch the governed execution flow below the assistant.',steps:['Choose “Balance + last five transactions” to see an approved account read.','Choose the $30,000 credit-limit request to see human approval enforced.','Choose “Security test” to see unauthorized account access blocked.','Change Transparency Level to Detailed to inspect the sanitized execution trace.'],voice:'Welcome to the Banking AI demonstration. Start with Balance and last five transactions to see an approved request. Next, try the thirty thousand dollar credit limit request to see a human approval checkpoint. Finally, run the Security test to see unauthorized access blocked. The execution panel explains each control.'
  }:path.includes('ai-operations')?{
    title:'How to use the AI Operations demo',intro:'Explore the control centre, then open either solution and trace its governance evidence.',steps:['Review the overview metrics and items needing attention.','Open Customer Banking Agent or Incentive and Commission from the left menu.','Use Requests, Exceptions and Approvals to follow operational work.','Open Control Library and Evidence Explorer to inspect governance and audit records.'],voice:'Welcome to the AI Operations demonstration. Begin on Overview to understand the active solutions and attention queue. Open either AI solution from the left menu. Then explore Requests, Exceptions, and Approvals. Finish with the Control Library and Evidence Explorer to review governance and audit evidence.'
  }:{
    title:'How to use the Commission demo',intro:'Run a synthetic commission scenario and follow its calculation, controls and evidence.',steps:['Select “Run new request” to open the processing scenarios.','Choose a standard scenario to see a validated result, or duplicate and compliance scenarios to see human review.','Open Exceptions and Approvals to inspect routed work.','Select “Inspect” in the current trace, then visit Audit evidence.'],voice:'Welcome to the Commission Operations demonstration. Select Run new request and choose a scenario. Standard scenarios validate automatically. Duplicate and compliance scenarios are routed for human review. Explore Exceptions and Approvals, inspect the current trace, and finish in Audit evidence.'
  };
  const launch=document.createElement('button');launch.className='demo-guide-launch';launch.type='button';launch.textContent='▶ How to use this demo';launch.setAttribute('aria-expanded','false');
  const panel=document.createElement('section');panel.className='demo-guide-panel';panel.hidden=true;panel.setAttribute('aria-label','Demo instructions');panel.innerHTML=`<div class="demo-guide-head"><h2>${profiles.title}</h2><button class="demo-guide-close" type="button" aria-label="Close instructions">×</button></div><div class="demo-guide-body"><p>${profiles.intro}</p><ol class="demo-guide-steps">${profiles.steps.map(step=>`<li>${step}</li>`).join('')}</ol><div class="demo-guide-actions"><button class="primary" type="button" data-voice="play">🔊 Play voice guide</button><button type="button" data-voice="stop">Stop voice</button><a href="/case-studies/">Case studies</a></div><p class="demo-guide-status" role="status" aria-live="polite"></p></div>`;
  document.body.append(launch,panel);
  const status=panel.querySelector('.demo-guide-status');
  launch.addEventListener('click',()=>{panel.hidden=!panel.hidden;launch.setAttribute('aria-expanded',String(!panel.hidden))});
  panel.querySelector('.demo-guide-close').addEventListener('click',()=>{panel.hidden=true;launch.setAttribute('aria-expanded','false')});
  panel.querySelector('[data-voice="play"]').addEventListener('click',()=>{if(!('speechSynthesis'in window)){status.textContent='Voice guidance is not supported in this browser.';return}window.speechSynthesis.cancel();const message=new SpeechSynthesisUtterance(profiles.voice);message.rate=.95;message.pitch=1;message.onstart=()=>status.textContent='Voice guide is playing.';message.onend=()=>status.textContent='Voice guide finished.';message.onerror=()=>status.textContent='Voice playback could not start. Follow the written steps above.';window.speechSynthesis.speak(message)});
  panel.querySelector('[data-voice="stop"]').addEventListener('click',()=>{if('speechSynthesis'in window)window.speechSynthesis.cancel();status.textContent='Voice guide stopped.'});
  window.addEventListener('beforeunload',()=>{if('speechSynthesis'in window)window.speechSynthesis.cancel()});
})();
